### ISSUE TITLE
Create new tab for Git CheatSheet

### ISSUE THREAD

**Issue by haxzie** [haxzie/GitMe#12]
Create a new tab "Cheat Sheet" under which it will contain basic git commands, most used and most useful commands with explanation.

**Comment by haxzie** [comment]
@jdemieville You can refer the [Gatsby Docs](https://www.gatsbyjs.org/docs/) to learn more about Gatsby. I've updated the Readme for setup instructions. Cheers :tada:

**Comment by jdemieville** [comment]
Thank you! I just ran into some issues running the project in my Cloud9 environment and was just about to start digging for Gatsby docs.

**Comment by haxzie** [comment]
Gatsby is pretty cool for creating websites on the go. And the community is great. Tip: If you loved working with Gatsby, try it out, create a beautiful website and submit a PR to showcase it on Gatsby's repo to get a free Gatsby Tshirt :heart:

**Comment by jdemieville** [comment]
Gatsby was really fun to learn! I will definitely try for a free Gatsby Tshirt, thanks for the info!
