### ISSUE TITLE
Convert the cards into simple lists

### ISSUE THREAD

**Issue by haxzie** [haxzie/GitMe#21]
Currently the submission page is displayed as cards, change it to a beautiful list. You can refer [this website](https://sosc.org.in/team) for an example.

**Comment by haxzie** [comment]
Sure. Go ahead :+1: if you need the source code code of the example website I have mentioned, you can find it [here](https://github.com/haxzie/sosc-website). It's up to your creativity to make it better than that :wink:

**Comment by jenniferkaplannyc** [comment]
How do I start up the repo on my local computer? I am trying to run `npm start`, but there is no start script.

**Comment by haxzie** [comment]
It's a Gatsby application. After running `npm install` you need to install Gatsby globally in your computer.
```
npm install --global gatsby-cli
```
and then to run the project, use ``` gatsby develop``

**Comment by haxzie** [comment]
@jenniferkaplannyc I have updated the Readme.md with instructions that might help you setting up the project. For any help or info, leave a comment or refer the [Gatsby docs](https://www.gatsbyjs.org/docs/) reagarding the project.

**Comment by jenniferkaplannyc** [comment]
Thank you! I’ll work on this tonight!
