### ISSUE TITLE
Fix Overflow of Navigation tabs in mobile devices

### ISSUE THREAD

**Issue by haxzie** [haxzie/GitMe#37]
Currently the navigation tabs break down into multiple lines on smaller screens, fix the styles to make it scroll-able through X direction. It's a beginner friendly issue. Do drop a comment if you'd love to work on the issue.

**Comment by binkpitch** [comment]
Can I take this issue?

**Comment by alekangelov** [comment]
@haxzie fixed this and made a pull request: https://github.com/haxzie/GitMe/pull/38

Cheers

**Comment by haxzie** [comment]
@alekangelov Thanks for the PR, but please do confirm with the maintainer before working on the issues :) so that no others will be working on the same.

@binkpitch Am really sorry that someone else submitted an issue before I could assign you, if you still like to contribute to the project, have a look at #39 :smile: Thank you for the interest. :100:
